### ISSUE TITLE
Kapitel zum Betrieb von FOSS für andere Kommunen

### ISSUE THREAD

**Issue by DirkGern** [missgreenwood/foss-concept#12]
> Die LHM als Serviceprovider, ist mMn nach ein Riesenthema. Dann muss man über SLAs etc. nachdenken. (Bei Kiwi haben wir es uns nicht getraut). Was passiert, wenn unser Service steht und eine andere Kommune nicht arbeiten kann? Code zur Verfügung zu stellen ist ein kleiner Schritt und durch die Lizenz abgesichert. Wichtig wäre aber schon, dass es einen Betreiber gibt, der das für mehrere Kommunen tut. Hier können wir aber nur darauf hinwirken auf politischer Ebene. Eigenes Kapitel?

Ich denke es macht Sinn, das als eigenes Kapitel aufzunehmen. Das ist ja sowohl bei beschaffter (z.B. Source code Verwaltung) als auch bei selbst entwickelter OSS ein Thema. 

> Hier können wir aber nur darauf hinwirken auf politischer Ebene. 

Da das hier ein politisches Papier ist, passt es ja. Wie gesagt, wenn unser Ziel ist, dass möglichst viele Kommunen (und damit Bürger*innen) an der Arbeit/Investitionen der LHM partizipieren können, dann müssen wir die Hürden zur Nutzung der Software minimieren. Minimal sind sie, wenn sie von einem vertrauenswürdigen Anbieter in der Cloud zur Verfügung gestellt werden.

Das muss ja im ersten Schritt nicht mit geschäftskritischen Anwendungen passieren (die kaufen die Kommunen eh bei AKDB un Co), sondern mit Anwendungen, bei denen es nett ist wenn man sie hat, wenn sie mal nicht zur Verfügung stehen, dann muss das Rathaus aber auch nicht geschlossen werden. Ein Beispiel für so etwas sind Verkehrszählungen. Das machen bestimmt viele Kommunen, aber nicht jeden Tag (auch die LHM macht das nicht jeden Tag). Entsprechend gibt es auch keine gute Software und schon gar kein Datenportal, auf dem der Bürger die Verkehrszählungen abrufen kann (wobei ich das Fass Open Data jetzt nicht aufmachen wollte ;)

_Originally posted by @xdoo in https://github.com/missgreenwood/foss-concept/pull/9#discussion_r500781511_

**Comment by hacklschorsch** [comment]
> Die LHM als Serviceprovider, ist mMn nach ein Riesenthema. 

Echt? Warum sollte die LHM Software für andere Kommunen betreiben? Oder tut sie das bereits?

**Comment by klml** [comment]
> Warum sollte die LHM Software für andere Kommunen betreiben? 

Wenn die LHM eine Software schon für sich selbst betreibt, ist eine Mandatierung für eine andere, vermutlich kleinere, Kommunen, vielleicht weniger Aufwand, als wenn die Gemeinde Kurzbach sich das auf einem Hetzner Server zusammenklicken muss. Das kann man vielleicht als Dienstleistung "verkaufen", in guter alter [Amtshilfe](https://de.wikipedia.org/wiki/Amtshilfe) leisten oder im Auftrag für einen kommunalen Spitzenverband liefern.

Ich denke aber an so etwas kann man sich ran trauen wenn die ersten FOSS Projekte stabil stehen und Kommunen ihren Betriebsbedarf nicht gedeckt bekommen.
