### ISSUE TITLE
Jeder Satz eine Zeile

### ISSUE THREAD

**Issue by klml** [missgreenwood/foss-concept#19]
Mir aufgefallen das wir bei einem kleinen fix (typo, link) die ursprünglichen contributor verlieren, da die ganze Zeile der fixenden Person zugeordnet wird.
Sieht man so im [blame](https://github.com/missgreenwood/foss-concept/blame/master/README.md)

Sollten wir in Zukunft jeden Satz als neue Zeile anlegen?
Dann bleibt die Urheberschaft für die anderen Sätze wenigstens erhalten.
Das könnte man auch in "Contribution Guidelines" einfließen lassen.

**Comment by missgreenwood** [comment]
Finde ich eine gute Idee. Magst Du das ändern, @klml?
