### ISSUE TITLE
Einleitung

### ISSUE THREAD

**Issue by klml** [missgreenwood/foss-concept#2]
Wir brauchen eine Einleitung was dieses Konzept definieren soll, woher es kommt und wo es gelten soll.

**Comment by klml** [comment]
mein Vorschlag dazu wäre https://github.com/klml/foss-concept/tree/preface

**Comment by missgreenwood** [comment]
Finde ich gut! :)

**Comment by klml** [comment]
;) fein, ich hab eine [PR](https://github.com/missgreenwood/foss-concept/pull/3) dazu gestellt

**Comment by missgreenwood** [comment]
:+1:
