### ISSUE TITLE
Wo geht die Reise hin? -> Description

### ISSUE THREAD

**Issue by hacklschorsch** [missgreenwood/foss-concept#4]
Hi @missgreenwood,

Danke für den Vorstoß. Ich freue mich auf die Zusammenarbeit :-)

Wenn ich richtig verstehe geht es hier um eine Begriffsdefinition - _Was ist FOSS?_ Ich schlage vor, Du schreibst das in die "Description" von dem Repo, damit es gleich klar ist:

> Was versteht die Stadt München unter dem Begriff Open Source?

oder

> Begriffsdefinition: FOSS (Free/Libre Open Source Software) im kommunalen Kontext

oder

> Open Source RULES!!!

oder so

?

Sonnige Grüße

Florian

**Comment by missgreenwood** [comment]
Hi @hacklschorsch, welcome! :)
Nehme ich gerne in die Description auf. Was wir hier eigentlich vorhaben, ist eine Open Source-Vision für die Stadt München. Wo und wie wollen wir Open Source einsetzen, was ist unsere Vision und wo wollen wir hin? Die Forderungen der grün-roten Koalition stehen im [Koalitionsvertrag](https://www.gruene-muenchen.de/wp-content/uploads/2020/04/Druckfassung_Koalitionsvertrag-2020_2026.pdf) auf S. 36, aber halt sehr kurz und knapp und nicht, warum wir das wollen und wo es hingehen soll.
