### ISSUE TITLE
Beachtung der XÖV-Standards

### ISSUE THREAD

**Issue by DirkGernhardt** [missgreenwood/foss-concept#7]
Beim Thema offene Standards sollten die XÖV-Standards (https://de.wikipedia.org/wiki/X%C3%96V) erwähnt werden. Diese Standards helfen beim Datenaustausch zwischen Behörden, vor allem zwischen Kommunen und Bundesregistern.

**Comment by missgreenwood** [comment]
Gute Idee, magst Du gleich einen Formulierungsvorschlag machen?

**Comment by hacklschorsch** [comment]
Die kannte ich gar nicht! Klasse. Gibt's dazu auch Internationale Pedants?

**Comment by missgreenwood** [comment]
Puh, da kenne ich mich jetzt gar nicht so aus. Frag vielleicht mal bei Matthias Moeser von Volt (https://twitter.com/matthiasmoeser) nach, der kennt sich zumindest für die europäische Ebene gut aus!
