### ISSUE TITLE
Eigenes Kapitel zu Fachanwendungen

### ISSUE THREAD

**Issue by DirkGernhardt** [missgreenwood/foss-concept#8]
Neben dem Thema Client-Betriebssystem und Office-Software sollte es auch ein eigenes Kapitel zu Fachanwendungen geben. Ich sehe hier ein großes Potenzial, Fachanwendungen gemeinsam mit anderen Kommunen auf Basis von OpenSource-Frameworks zu entwickeln, die dann wiederum allen Kommunen oder auch kommunalen IT-Dienstleistern zur Verfügung gestellt werden könnten.

**Comment by missgreenwood** [comment]
Gute Idee. Wenn Du Vorschläge hast, nur zu!

**Comment by klml** [comment]
Zum Thema **Fachanwendungen als Eigenentwicklungen** gibt es bereits einen Antrag, der ist noch auf "klassischem Wege" ;) entstanden, bald aber abgestimmt wird. Daher würde ich warten bis der *hoffentlich* durch ist.

Natürlich sind Fachanwendungen nicht alle Eigenentwicklungen, sondern können auch beschafft werden, was wieder mit dem Abschnitt [Beschaffung](https://github.com/missgreenwood/foss-concept#beschaffung) zusammenhängt.
Aber tatsächlich sollte man "Fachanwendungen" als Abschnitt aufnehmen.

**Comment by DirkGernhardt** [comment]
Wird in dem Antrag auf die Strategie zu Fachanwendungen eingegangen? Kannst du einen Link senden? Ich hätte jetzt einfach 3 - 4 Absätze zu beschafften und eigenentwickelten Fachanwendungen geschrieben.

**Comment by missgreenwood** [comment]
Wir konnten den Antrag gestern endlich stellen, ich schicke ihn Dir per Email, @DirkGernhardt. :)

**Comment by missgreenwood** [comment]
Der Antrag ist natürlich auch im offiziellen Ratsinformationssystem zu finden: https://www.ris-muenchen.de/RII/RII/DOK/ANTRAG/6289795.pdf

**Comment by DirkGern** [comment]
Das Issue kann auch geschlossen werden.
